"""add cita

Revision ID: abfd02745f2f
Revises: efa071de5f65
Create Date: 2021-10-18 22:14:50.301391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abfd02745f2f'
down_revision = 'efa071de5f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citas', sa.Column('fecha', sa.Date(), nullable=True))
    op.add_column('citas', sa.Column('hora', sa.Time(), nullable=True))
    op.drop_column('citas', 'fecha_hora')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citas', sa.Column('fecha_hora', sa.DATETIME(), nullable=True))
    op.drop_column('citas', 'hora')
    op.drop_column('citas', 'fecha')
    # ### end Alembic commands ###
